---
- name: Create kafka-ui user and group
  ansible.builtin.include_tasks: user.yml

- name: Install kafka-ui
  ansible.builtin.include_tasks: install.yml

- name: Configure kafka-ui
  ansible.builtin.include_tasks: configure.yml
