---
- name: Create kafka-ui group
  ansible.builtin.group:
    name: "{{ kafka_ui_group }}"
    state: present

- name: Create kafka-ui user
  ansible.builtin.user:
    name: "{{ kafka_ui_user }}"
    group: "{{ kafka_ui_group }}"
    shell: /bin/false
    home: "{{ kafka_ui_install_dir }}"
    create_home: false
    system: true
